# comment

include Makefile.in
-include Makefile.doesntexist

.PHONY: all

all: target

foo = bar $(var) \
    $(baz) quux

<beginfold id='2'>ifeq</beginfold id='2'> ($(CC),gcc)
    bla=$(call func,param1,param2)
<endfold id='2'></endfold id='2'><beginfold id='2'>else</beginfold id='2'> ifeq "x" "y"
    $(error this seems wrong)
<endfold id='2'></endfold id='2'><beginfold id='2'>else</beginfold id='2'>
    libs=$(normal_libs)
<endfold id='2'>endif</endfold id='2'>

target1:
        error

target2: bla.cpp $@
	$(CC) bla.c -o bla.o
	$(CC) bla.o $< \
	    -o bla.exe
	@echo "hello"
