erDiagram
    direction TB

    CUSTOMER:::someclass ,  someclass ||--o{ ORDER:::someclass
          : places
    CUSTOMER {
        string name
        string custNumber
        string sector
    }

    ORDER ||--|{ LINE-ITEM :
         contains
    ORDER["sdsds"]:::someclass {
        int orderNumber
        string deliveryAddress
    }
    LINE-ITEM[plop] {
        string(ds) productCode PK  ,  FK,PK
            "Dsds"
        *int[dsds] *quantity
              PK"The license #"
        _float pricePerUnit"Only 99 characters are allowed"
        %% 2 fields
        a b c
    }

    CAR
      1
        to
          zero or more
        NAMED-DRIVER : allows
    PERSON
      many(0)
         optionally to
           0+
             NAMED-DRIVER : is


    style CAR,LINE-ITEM fill:#f9f,stroke:#333,stroke-width:4px

    classDef someclass fill:#f96
    classDef default stroke-width:1px;
