# comment

a_1: # comment

  101

b: true
C <

  # comment
  a: 117,
>
d: {

  a: 117, # comment
}
e: [

  # comment
  "a", "b" # comment
]
# comment
f: MY_ENUM
g: "124"
h: "116 \000 \377"
[type.googleapis.com/google.rpc.ErrorInfo] {
  reason: "NOT_FOUND"
}
[a_b.c_d]

 {
  a: 123 # comment
}
multistring: "abc (עולם) 321" "hello\n" # comment
multiline: # comment
  "abc" # comment
  "def"
