graph TD
  accTitle: Big Decisions
  accDescr: Bob's Burgers process for making big decisions
  accDescr {
    The official Bob's Burgers corporate processes that are used
    for making very, very big decisions.
  }

  classDef sub opacity:0
  classDef note fill:#ffd, stroke:#ccb

  a---b
  a-----b
  a-->b
  a---->b
  a<---b
  a<----b
  a<-->b
  a<---->b
  a--xb
  a----xb
  a x---b
  a x----b
  a x--ob
  a x----ob
  a--ob
  a----ob
  a o---d
  a o----b
  a o--xb
  a o----xb

  a<--note---d
  a x--"note"---d
  a o--"no"te -->d
  a<--""note---b
  a-- """a""``"note-->b
  a-- a"a"note-->-b

  a-->|note|b

  a===b
  a=====b
  a==>b
  a====>b
  a<===d
  a<====b
  a<==>b
  a<====>b
  a==xb
  a====xb
  a x===ds
  a x====b
  a x==ob
  a x====ob
  a==ob
  a====ob
  a o===d
  a o====b
  a o==xb
  a o====xb

  a<==note===d
  a o=="note"==>d
  a x=="no"te ===ds
  a<==""note===b
  a== """a""``"note==>b
  a==a"a"note==>-b

  a===|note|b

  a-.-b
  a-...-b
  a-.->b
  a-...->b
  a-.-xb
  a-...-xb
  a-.-ob
  a-...-ob
  a<-.-b
  a<-...-b
  a x-.-b
  a x-...-b
  a o-.-b
  a o-...-b

  a<-.note.-b
  a-.note..-b
  a-.note.->b
  a-.note.-xb
  a-.note.-ob
  a x-.note.-b
  a o-.note..-b
  a o-.note..--b

  a o-.-|note|b

  a~~~b
  a~~~~~b

  A & B --> C & D

  A
  ---
  B

  a["<img ds class='sd#quot;s' ds="ds
  "
  %% this a comment
  src="pipe.jpg"/> is not a <b>pipe</b>" bla "" bla "``" bla]

  a["`<img ds class='sd#quot;s' ds="ds
  "
  %% this a comment
  src="pipe.jpg"/> is not a <b>pipe</b>`" bla "" bla "``" bla]

  a[<img ds class='sd#quot;s' ds="ds
  "
  %% this a comment
  src="pipe.jpg"/> is not a <b>pipe</b> bla "" bla "``" bla]

  a["text
     text
     %% bad quot
  "  text"]

  A e1@==> B
  e1@{ animate: true }
  A@{"label": dsds}
  %% oups, no label
  A@{label:dsds}
  A@{label: dsds}

  subgraph subC ["ssasa"]
      C
      noteC[I AM THE THIRD NOTE<br>...WITH 2 LINES]
  end

  class noteA,noteB,noteC note
  classDef firstClassName,secondClassName fill:#f9f,stroke:#333,stroke-width:4px

  linkStyle 1,2,7 stroke:#ff3,stroke-width:4px,color:red;
  %% color followed by ';' is an entity
  style 1,0 stroke-width:4px,stroke:ds#dsdsds;a--->a

  %% click keyword
  click --- abc;
  click D href "https://www.github.com" "Open this in a new tab" _blank
  %% click node
  click;
  click--- up
  click[click] --- down
