gitGraph TB:
commit
branch develop
%% no space
branch"tag-"
%% invalid name (is a kw)
branch cherry-pick
%% ok
branch cherry-pick- order: 2
branch "cherry-pick" order: 2
checkout main
commit id:"ash" tag:"v1.0.0"
commit
checkout main
cherry-pick id:"MERGE" parent:"B"
merge nice_feature id: "customID" tag: "customTag" type: REVERSE %% comment
commit type: HIGHLIGHT
commit
merge develop
