requirementDiagram

% a bad comment, because mermaid...
%% a comment

requirement test_req:::important {
    id: 123
    text: "class styling example"
    risk: low
    %% error on "lo"
    risk: lo
    verifymethod: test
    VerifyMethoD: TesT
}
testreq:::important

element "__a__c__*abx*__a__c__<b>abc&lt;abc#abc;&abc#abc\*x\_ y" {
    docref: bla bla
    docref: + oups
    docref: é oups
    docref: but ok for é...
    % error: unknown doref + < + >
    doref: __a__c__*abx*__a__c__<b>abc&lt;abc#abc;&abc#abc\*x\_ y
}

element __a__c__*abx*__a__c__<b>abc&lt;abc#abc;&abc#abc\*x\_ y {
    type: direction functionalRequirementrequirementDiagra0dsd ds s++%% simulation %% ds element
    %% error on "id"
    type: Id is a keyword
}
a:::  im portant

test_entity <- satisfies - "test_req"
"test_entity" - satisfies -> test_req
&lt;entity - unknown -> &lt;entity"x

classDef important font-weight:bold
classDef "important" font-weight:bold
classDef important , "a" font-weight:bold
classDef "important" , a*b*c font-weight:bold

class entity important , a*b*c
class "testa entity" important , "a"
class entity , "a" "important" , a*b*c
class "testa entity" , a*b*c "important" , "a"

style entity fill:#93f,stroke:#333
style "testa entity" fill:#93f,stroke:#333
style entity , "a" fill:#93f,stroke:#333
style "testa entity" , a*b*c fill:#93f,stroke:#333
