timeline
    title Timeline of Revolution
    section 17th-20th century
        1.0 : Machinery, Water power, Steam <br>power
        Industry : Electricity : Internal:combustion: engine, Mass production
        Industry 3.0: Electronics, Computers, Automation
    section 21st century
        % node
        section: Internet
        % node
        section : Internet
        % section
        section  : Internet
        % section
        section x: Internet
        % node
        section-4 : Internet
        title-4 : Internet
