rule-set =  alt1 / alt2 ; bla bla
rule-set =/ alt3
; bla bla
repeat = 3DIGIT 1*2DIGIT 1*DIGIT 1*( rule / (*c-wsp c-nl) )
rule   = [repeat] element "(" *c-wsp 1*2<element> *c-wsp ")"
bin    = %b1001-10 %b101.1101.10101 %b1h %b11-1h %b1.h.1
dec    = %d1239-23 %d23.3455.1 %d1h %d11-1h %d1.h.1
hex    = %xf9-0a %xaf.55.d1 %x1h %x11-1h %x1.h.1
str    = "str" %i"str" %s"str"
