journey
  title bla <b>bla: #lt; bla #bla

  Title
    bla <b>bla #lt; bla #bla

  Title

    oups

  section bla <b>bla: #lt; bla #bla
  
  section
    bla <b>bla: #lt; bla #bla

  section

    oups

  task : 3.4 : Me,Cat#lt;,:Cat#Me
