mindmap
  root((mindmap))
    id[I am a square]
    id(I am a rounded square)
    id((I am a circle))
    id))I am a bang((
    id)I am a cloud(
    id{{I am a hexagon}}
    id["I am a square" ]
    %%                ~ oups
    Origins
      Long history 
      ::icon(fa fa-book)
      Popularisation
        British popular psychology author Tony Buzan
    Research
      On effectiveness<br/>and features
      On **Automatic** creation
        Uses
            Creative techniques $$sin f$$
            :::urgent large
            Strategic planning
            Argument mapping
    Tools
      Pen __and__ paper
      Mermaid
