sequenceDiagram
    autonumber
    participant Alice as A
    participant Bob@{ "type" : "collections" }
    box rgb(from hwb(120deg 10% 20%) r g calc(b + 200)) Group Description
        participant Alice Bob@{ "type" : "collections" }
    end
    box Aqua Group Description
        participant Alice and Bob as P as p
    end
    link Alice: Dashboard @ https://example.com/alice
    links John: {"Dashboard": "https://example.com/john", "Wiki": "https://example.com/john"}

    A->B
    A->>B
    A-xB
    A-)B
    A-//B
    A-\\B
    A-|/B
    A-|\B
    A//-B
    A\\-B
    A/|-B
    A\|-B

    A-->B
    A-->>B
    A--xB
    A--)B
    A--//B
    A--\\B
    A--|/B
    A--|\B
    A//--B
    A\\--B
    A/|--B
    A\|--B

    A<<->>B
    A<<-->>B
    A()<<-->>()B

    %% oups
    A-A--B
    %% ok
    A-A-->B

    %% only <br\s*>
    A  ->   Bob: Queue *message*<br><br/><br /><b>dsds</b>
    Bob->>S: Queue response
    create participant Carl
    Alice-xCarl: Hi $$\pi$$!
    create actor D as Donald
    Carl--xD: Hi!
    destroy Carl
    Alice-xCarl: We are too many
    activate John
    John-->>Alice: I #9829; you #infin; times more!
    deactivate John
    Alice->>+John: Hello John, how are you?
    John-->>-Alice: Great!

    Note right of John: Text in note
    Note over Alice,John: A typical interaction

    loop Every minute
        John-->Alice: Great!
    end

    alt is sick
        Bob->>Alice: Not so good :(
    else is well
        Bob->>Alice: Feeling fresh like a daisy
    end
    opt Extra response
        Bob->>Alice: Thanks for asking
    end

    par Alice to Bob
        Alice->>Bob: Hello guys!
    and Alice to John
        Alice->>John: Hello guys!
    end

    critical Establish a connection to the DB
        Service-->DB: connect
    option Network timeout
        Service-->Service: Log error
    end

    break when the booking process fails
        API-->Consumer: show failure
    end

    rect rgb(200, 150, 255)
        Alice->>+John: John, can you hear me?
        John-->>-Alice: Hi Alice, I can hear you!
    end
